module.exports = {
  "string.alphanum": "{{#label}} 只能包含英文字母和数字",
  "string.base": "{{#label}} 必须为字符串",
  "string.base64": "{{#label}} 不是合法的 base64 字符串",
  "string.creditCard": "{{#label}} 必须为卡号",
  "string.dataUri": "{{#label}} 不是合法的 dataUri 字符串",
  "string.domain": "{{#label}} 必须包含合法的域名",
  "string.email": "{{#label}} 必须为邮箱地址",
  "string.empty": "{{#label}} 不能为空",
  "string.guid": "{{#label}} 不是合法的 GUID",
  "string.hex": "{{#label}} 只能包含十六进制字符",
  "string.hexAlign": "{{#label}} 十六进制解码表示必须字节对齐",
  "string.hostname": "{{#label}} 必须为合法的 hostname",
  "string.ip": "{{#label}} 必须为合法的 IP 地址，并带有 {{#cidr}} CIDR",
  "string.ipVersion":
    "{{#label}} 必须为合法的 IP {{#version}} 地址，并带有 {{#cidr}} CIDR",
  "string.isoDate": "{{#label}} 必须为 iso 格式",
  "string.isoDuration": "{{#label}} 必须是有效的 ISO 8601 时间段",
  "string.length": "{{#label}} 长度应等于{{#limit}}",
  "string.lowercase": "{{#label}} 只能包含小写字母",
  "string.max": "{{#label}} 长度应小于等于{{#limit}}",
  "string.min": "{{#label}} 长度至少为{{#limit}}",
  "string.normalize": "{{#label}} 必须以 {{#form}} 形式进行 unicode 规范化",
  "string.token": "{{#label}} 只能包含英文字母，数字和下划线(_)",
  "string.pattern.base": "{{#label}} {:[.]} 不能匹配模式 {{#regex}}",
  "string.pattern.name": "{{#label}} {:[.]} 不能匹配模式 {{#name}}",
  "string.pattern.invert.base": "{{#label}} {:[.]} 匹配了模式 {{#regex}}",
  "string.pattern.invert.name": "{{#label}} {:[.]} 匹配了模式 {{#name}}",
  "string.trim": "{{#label}} 字符串前后不能含有空格",
  "string.uri": "{{#label}} 必须为合法的 URI 地址",
  "string.uriCustomScheme": "{{#label}} 必须为合法的 {{#scheme}} 格式 URI 地址",
  "string.uriRelativeOnly": "{{#label}} 必须为合法的相对路径",
  "string.uppercase": "{{#label}} 只能包含大写字母",
};
